# Generated by Django 6.0.3 on 2026-05-17 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TuringMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('states', models.JSONField(default=list)),
                ('input_alphabet', models.JSONField(default=list)),
                ('tape_alphabet', models.JSONField(default=list)),
                ('initial_state', models.CharField(max_length=80)),
                ('final_states', models.JSONField(default=list)),
                ('blank_symbol', models.CharField(max_length=20)),
                ('transitions', models.JSONField(default=dict)),
                ('source', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_string', models.CharField(blank=True, max_length=500)),
                ('tape', models.JSONField(default=dict)),
                ('head_position', models.IntegerField(default=0)),
                ('current_state', models.CharField(max_length=80)),
                ('steps', models.PositiveIntegerField(default=0)),
                ('max_steps', models.PositiveIntegerField(default=1000)),
                ('status', models.CharField(choices=[('RUNNING', 'En ejecución'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada'), ('TIMEOUT', 'No termina')], default='RUNNING', max_length=20)),
                ('history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='simulator.turingmachine')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
